services:
  - type: web
    name: flask-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn "app:create_app()"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DB_USER
        value: postgres_web
      - key: DB_NAME
        value: web_tb1a
      - key: DB_PORT
        value: 5432
      - key: SECRET_KEY
        generateValue: true
      # Эти значения нужно установить через веб-интерфейс
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DATABASE_URL
        sync: false 